SELECT COUNT(FECHA) FROM ingresos WHERE DATE(FECHA) = CURDATE() AND TIPO_INGRESO = 1;
SELECT COUNT(*) AS TOTAL_ESTUDIANTES FROM usuario WHERE ROL = 'estudiante';
SELECT DATE(FECHA) AS FECHA, COUNT(*) AS CANTIDAD_INGRESOS FROM ingresos GROUP BY DATE(FECHA);

SELECT DATE(FECHA) AS FECHA, SUM(CANTIDAD_INGRESOS) AS TOTAL_INGRESOS FROM (
  SELECT DATE(FECHA) AS FECHA, COUNT(*) AS CANTIDAD_INGRESOS FROM ingresos GROUP BY DATE(FECHA)
) AS INGRESOS_POR_FECHA
GROUP BY FECHA;

SELECT DATE_FORMAT(fecha, '%Y-%m') AS mes,  
       AVG(ROUND(cantidad_ingresos, 1)) AS PROMEDIO 
FROM (
  SELECT DATE(fecha) AS fecha, COUNT(*) AS cantidad_ingresos 
  FROM ingresos 
  GROUP BY DATE(fecha)
) AS ingresos_por_fecha
GROUP BY mes;


